### PR TITLE
Update to actually support deployment on Netlify

### LINKED ISSUE #1: Publish somewhere
Glitch was too slow to be used by public.

We discussed heroku, katja's droplet, or netlify

@danfishgold - post any progress here. I'm not assigning to you, but have done nothing yet, myself and thought it would be good to keep each other in the loop via issue!

### PR DESCRIPTION
**Pull request by danfishgold**
Resolve #1 via [pdf-maker.netlify.app](https://pdf-maker.netlify.app)

This was more complicated than I expected. Several issues came up:

## 1. Package dependencies

Netlify functions don't automatically install the dependencies in their `package.json`.

An error in the build log asked me to add a plugin to `netlify.toml`:

```toml
[[plugins]]
package = "@netlify/plugin-functions-install-core"
```

## 2. The bundle size was too big

`puppeteer` is about 250MB, but Netlify functions (which wrap around AWS Lambdas) only allow about 66MB. Instead of using `puppeteer`, I followed the instructions in this [wonderful blog post](https://bitsofco.de/how-to-use-puppeteer-in-a-netlify-aws-lambda-function/) and installed `puppeteer-core` and `chrome-aws-lambda`.

## 3. A local dev issue

`chrome-aws-lambda` tries to be smart about using different version of `puppeteer` on the serverless infrastructure and during local development, but `netlify dev` doesn't roll with that, so I had to tell which environment was running the code via the `NETLIFY_DEV` environment variable.

Furthermore, Netlify installs dev dependencies so I couldn't include `puppeteer` in `devDependencies` and I couldn't include `require('puppeteer')` in the code because it greps for package names in function code. I think.

I cheated with `require('puppet' + 'eer')` and it seems to work.

## 4. Fonts

Headless Chromium doesn't come with any fonts other than Open Sans. `chrome-aws-lambda` has a solution for this (detailed in [the package's docs](https://github.com/alixaxel/chrome-aws-lambda#fonts), so I had to manually include a monospace font (I chose Roboto Mono only because it was the first search result) using `chromium.font`.

### CODE REVIEW

**Comment by danfishgold** [comment]
[check it out](https://deploy-preview-3--pdf-maker.netlify.app)

**Review by katjam — APPROVED** [review]
:grimacing: Nothing  is ever as simple as we imagine! Let's give this a go.

**Review by katjam — COMMENTED** [review]
Maybe also add some note to the `index.html` that it takes a little time. Or a message confirming that download has started. At first appears that nothing happens.

**Comment by danfishgold** [comment]
whoo!

**Pull request merged**
